### ISSUE TITLE
Behavior when failing to parse?

### ISSUE THREAD

**Issue by JonathanWilbur** [jugglerchris/rust-html2text#85]
What is the behavior of this package when it fails to parse HTML? I don't see a `Result` type being returned from `from_read`, so am I correct in assuming that this panics if it is asked to parse invalid HTML?

**Comment by JonathanWilbur** [comment]
(This issue could be thought of as a documentation issue, since I don't see anywhere in the docs that this important detail is mentioned.)

**Comment by jugglerchris** [comment]
Hi,
The HTML parser used (html5ever) doesn't have any way of returning a parse error - instead you'll get a document anyway (the spec has rules for handling what would otherwise be considered parse errors).

It can, however, return an I/O error (if passed an input stream which returns an error) - and currently `html2text` just unwraps, so that would indeed panic.  I guess it would be better to pass the `Err` and let the caller do what it wants with it.

Otherwise any panic is a bug!
